name: "actions-env"
description: "Create ENV File using GitHub Actions with GitHub's Secret"
author: "Jericho Aquino"
branding:
  icon: "box"
  color: "blue"
inputs:
  examplefile:
    description: "Example File name"
    required: false
    default: ".env.example"
  targetfile:
    description: "Target File name"
    required: false
    default: ".env"
  prefix:
    description: "Prefix for secret"
    required: false
    default: "ENV_"
  env:
    description: "Environment variables"
    required: false
    default: ""
runs:
  using: "node16"
  main: "index.js"
